
name: Java CI with Maven 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCR_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Configurer Docker pour GCR
      run: gcloud auth configure-docker europe-west1-docker.pkg.dev 

    - name: "Construire l'image Docker"
      run: |
          IMAGE_NAME=gcr.io/${{secrets.GCP_PROJECT_ID}}/hello-world
          TAG=$(git rev-parse --short HEAD)
          docker build -t $IMAGE_NAME:$TAG -t $IMAGE_NAME:latest .

    - name: Pousser l'image vers GCR
      run: |
          IMAGE_NAME=gcr.io/${{secrets.GCP_PROJECT_ID}}/hello-world
          TAG=$(git rev-parse --short HEAD)
          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:latest
      
      
